name: Java CI + Commit Lint

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate commits with commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project with Maven
        run: mvn clean install
